Fixing NoSuchMethodError:ConcurrentHashMap.keySet When running code with jre 7 but compiled with jdk 8 there are a lot of errors saying: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView
To fix it use Map interface instead of ConcurrentHashMap
http://stackoverflow.com/questions/32954041/concurrenthashmap-crashing-application-compiled-with-jdk-8-but-targeting-jre-7